#![allow(clippy::cmp_owned, clippy::iter_cloned_collect)]

mod browser_actions;
mod browser_core;
mod browser_selection;
mod collections;
mod common;
mod drag_drop_folders;
mod drag_drop_drop_targets;
mod drag_drop_selection;
mod drag_drop_waveform;
mod external_drop_import;
mod focus_random;
mod folders_core;
mod folders_search;
mod missing;
mod playback_loop;
mod recording;
mod selection_bpm_scale;
mod selection_undo;
mod transient_options;
mod trash;
mod waveform;
mod waveform_nav_cursor;
mod waveform_nav_render;
