use super::types::{HotkeyAction, HotkeyCommand, HotkeyGesture, HotkeyScope, KeyPress};
use crate::egui_app::state::FocusContext;
use egui::Key;

pub(super) const HOTKEY_ACTIONS: &[HotkeyAction] = &[
    HotkeyAction {
        id: "undo-ctrl-z",
        label: "Undo",
        gesture: HotkeyGesture::with_command(Key::Z),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::Undo,
    },
    HotkeyAction {
        id: "undo-u",
        label: "Undo",
        gesture: HotkeyGesture::new(Key::U),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::Undo,
    },
    HotkeyAction {
        id: "redo-ctrl-y",
        label: "Redo",
        gesture: HotkeyGesture::with_command(Key::Y),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::Redo,
    },
    HotkeyAction {
        id: "redo-shift-u",
        label: "Redo",
        gesture: HotkeyGesture::with_shift(Key::U),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::Redo,
    },
    HotkeyAction {
        id: "toggle-select",
        label: "Toggle selection",
        gesture: HotkeyGesture::new(Key::X),
        scope: HotkeyScope::Focus(FocusContext::SampleBrowser),
        command: HotkeyCommand::ToggleFocusedSelection,
    },
    HotkeyAction {
        id: "toggle-folder-select",
        label: "Toggle folder selection",
        gesture: HotkeyGesture::new(Key::X),
        scope: HotkeyScope::Focus(FocusContext::SourceFolders),
        command: HotkeyCommand::ToggleFolderSelection,
    },
    HotkeyAction {
        id: "delete-folder",
        label: "Delete folder",
        gesture: HotkeyGesture::new(Key::D),
        scope: HotkeyScope::Focus(FocusContext::SourceFolders),
        command: HotkeyCommand::DeleteFocusedFolder,
    },
    HotkeyAction {
        id: "rename-folder",
        label: "Rename folder",
        gesture: HotkeyGesture::new(Key::R),
        scope: HotkeyScope::Focus(FocusContext::SourceFolders),
        command: HotkeyCommand::RenameFocusedFolder,
    },
    HotkeyAction {
        id: "rename-sample",
        label: "Rename sample",
        gesture: HotkeyGesture::new(Key::R),
        scope: HotkeyScope::Focus(FocusContext::SampleBrowser),
        command: HotkeyCommand::RenameFocusedSample,
    },
    HotkeyAction {
        id: "rename-collection",
        label: "Rename collection",
        gesture: HotkeyGesture::new(Key::R),
        scope: HotkeyScope::Focus(FocusContext::CollectionsList),
        command: HotkeyCommand::RenameFocusedCollection,
    },
    HotkeyAction {
        id: "rename-collection-from-samples",
        label: "Rename collection",
        gesture: HotkeyGesture::new(Key::R),
        scope: HotkeyScope::Focus(FocusContext::CollectionSample),
        command: HotkeyCommand::RenameFocusedCollection,
    },
    HotkeyAction {
        id: "new-folder",
        label: "New folder",
        gesture: HotkeyGesture::new(Key::N),
        scope: HotkeyScope::Focus(FocusContext::SourceFolders),
        command: HotkeyCommand::CreateFolder,
    },
    HotkeyAction {
        id: "search-folders",
        label: "Search folders",
        gesture: HotkeyGesture::new(Key::F),
        scope: HotkeyScope::Focus(FocusContext::SourceFolders),
        command: HotkeyCommand::FocusFolderSearch,
    },
    HotkeyAction {
        id: "search-browser",
        label: "Search samples",
        gesture: HotkeyGesture::new(Key::F),
        scope: HotkeyScope::Focus(FocusContext::SampleBrowser),
        command: HotkeyCommand::FocusBrowserSearch,
    },
    HotkeyAction {
        id: "find-similar",
        label: "Toggle find similar",
        gesture: HotkeyGesture::with_shift(Key::F),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::FindSimilarFocusedSample,
    },
    HotkeyAction {
        id: "select-all-browser",
        label: "Select all samples",
        gesture: HotkeyGesture::with_command(Key::A),
        scope: HotkeyScope::Focus(FocusContext::SampleBrowser),
        command: HotkeyCommand::SelectAllBrowser,
    },
    HotkeyAction {
        id: "normalize-browser",
        label: "Normalize sample",
        gesture: HotkeyGesture::new(Key::N),
        scope: HotkeyScope::Focus(FocusContext::SampleBrowser),
        command: HotkeyCommand::NormalizeFocusedSample,
    },
    HotkeyAction {
        id: "normalize-collection",
        label: "Normalize sample",
        gesture: HotkeyGesture::new(Key::N),
        scope: HotkeyScope::Focus(FocusContext::CollectionSample),
        command: HotkeyCommand::NormalizeFocusedSample,
    },
    HotkeyAction {
        id: "normalize-waveform",
        label: "Normalize selection/sample",
        gesture: HotkeyGesture::new(Key::N),
        scope: HotkeyScope::Focus(FocusContext::Waveform),
        command: HotkeyCommand::NormalizeWaveform,
    },
    HotkeyAction {
        id: "delete-browser",
        label: "Delete sample",
        gesture: HotkeyGesture::new(Key::D),
        scope: HotkeyScope::Focus(FocusContext::SampleBrowser),
        command: HotkeyCommand::DeleteFocusedSample,
    },
    HotkeyAction {
        id: "delete-collection",
        label: "Delete sample",
        gesture: HotkeyGesture::new(Key::D),
        scope: HotkeyScope::Focus(FocusContext::CollectionSample),
        command: HotkeyCommand::DeleteFocusedSample,
    },
    HotkeyAction {
        id: "add-to-collection",
        label: "Add to collection",
        gesture: HotkeyGesture::new(Key::C),
        scope: HotkeyScope::Focus(FocusContext::SampleBrowser),
        command: HotkeyCommand::AddFocusedToCollection,
    },
    HotkeyAction {
        id: "crop-selection",
        label: "Crop selection",
        gesture: HotkeyGesture::new(Key::C),
        scope: HotkeyScope::Focus(FocusContext::Waveform),
        command: HotkeyCommand::CropSelection,
    },
    HotkeyAction {
        id: "crop-selection-new-sample",
        label: "Crop selection as new sample",
        gesture: HotkeyGesture::with_shift(Key::C),
        scope: HotkeyScope::Focus(FocusContext::Waveform),
        command: HotkeyCommand::CropSelectionNewSample,
    },
    HotkeyAction {
        id: "save-selection-to-browser",
        label: "Save selection/slices to browser",
        gesture: HotkeyGesture::new(Key::Enter),
        scope: HotkeyScope::Focus(FocusContext::Waveform),
        command: HotkeyCommand::SaveSelectionToBrowser,
    },
    HotkeyAction {
        id: "show-hotkeys",
        label: "Show hotkeys",
        gesture: HotkeyGesture::with_command(Key::Slash),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::ToggleOverlay,
    },
    HotkeyAction {
        id: "copy-status-log",
        label: "Copy status log",
        gesture: HotkeyGesture {
            first: KeyPress {
                key: Key::L,
                command: true,
                shift: true,
                alt: false,
            },
            chord: None,
        },
        scope: HotkeyScope::Global,
        command: HotkeyCommand::CopyStatusLog,
    },
    HotkeyAction {
        id: "submit-github-issue",
        label: "Submit GitHub issue",
        gesture: HotkeyGesture::with_shift(Key::F1),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::OpenFeedbackIssuePrompt,
    },
    HotkeyAction {
        id: "toggle-loop",
        label: "Toggle loop",
        gesture: HotkeyGesture::new(Key::L),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::ToggleLoop,
    },
    HotkeyAction {
        id: "focus-waveform",
        label: "Focus waveform",
        gesture: HotkeyGesture::with_chord(KeyPress::new(Key::G), KeyPress::new(Key::W)),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::FocusWaveform,
    },
    HotkeyAction {
        id: "focus-browser",
        label: "Focus source samples",
        gesture: HotkeyGesture::with_chord(KeyPress::new(Key::G), KeyPress::new(Key::S)),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::FocusBrowserSamples,
    },
    HotkeyAction {
        id: "focus-collection-samples",
        label: "Focus collection samples",
        gesture: HotkeyGesture::with_chord(KeyPress::new(Key::G), KeyPress::new(Key::C)),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::FocusCollectionSamples,
    },
    HotkeyAction {
        id: "focus-sources-list",
        label: "Focus sources list",
        gesture: HotkeyGesture::with_chord(KeyPress::new(Key::G), KeyPress::with_shift(Key::S)),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::FocusSourcesList,
    },
    HotkeyAction {
        id: "focus-collections-list",
        label: "Focus collections list",
        gesture: HotkeyGesture::with_chord(KeyPress::new(Key::G), KeyPress::with_shift(Key::C)),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::FocusCollectionsList,
    },
    HotkeyAction {
        id: "play-random-sample",
        label: "Play random sample",
        gesture: HotkeyGesture {
            first: KeyPress::with_shift(Key::R),
            chord: None,
        },
        scope: HotkeyScope::Global,
        command: HotkeyCommand::PlayRandomSample,
    },
    HotkeyAction {
        id: "toggle-random-navigation-mode",
        label: "Toggle random navigation mode",
        gesture: HotkeyGesture {
            first: KeyPress::with_alt(Key::R),
            chord: None,
        },
        scope: HotkeyScope::Global,
        command: HotkeyCommand::ToggleRandomNavigationMode,
    },
    HotkeyAction {
        id: "play-previous-random-sample",
        label: "Play previous random sample",
        gesture: HotkeyGesture {
            first: KeyPress {
                key: Key::R,
                command: true,
                shift: true,
                alt: false,
            },
            chord: None,
        },
        scope: HotkeyScope::Global,
        command: HotkeyCommand::PlayPreviousRandomSample,
    },
    HotkeyAction {
        id: "move-trashed-to-folder",
        label: "Move trashed samples to folder",
        gesture: HotkeyGesture::new(Key::P),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::MoveTrashedToFolder,
    },
    HotkeyAction {
        id: "move-trashed-to-folder-shift",
        label: "Move trashed samples to folder",
        gesture: HotkeyGesture::with_shift(Key::P),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::MoveTrashedToFolder,
    },
    HotkeyAction {
        id: "tag-trash",
        label: "Trash sample(s)",
        gesture: HotkeyGesture::new(Key::OpenBracket),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::TagTrashSelected,
    },
    HotkeyAction {
        id: "tag-keep",
        label: "Keep sample(s)",
        gesture: HotkeyGesture::new(Key::CloseBracket),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::TagKeepSelected,
    },
    HotkeyAction {
        id: "tag-neutral",
        label: "Neutral sample(s)",
        gesture: HotkeyGesture::new(Key::Quote),
        scope: HotkeyScope::Global,
        command: HotkeyCommand::TagNeutralSelected,
    },
    HotkeyAction {
        id: "trim-selection",
        label: "Trim selection",
        gesture: HotkeyGesture::new(Key::T),
        scope: HotkeyScope::Focus(FocusContext::Waveform),
        command: HotkeyCommand::TrimSelection,
    },
    HotkeyAction {
        id: "reverse-selection",
        label: "Reverse selection",
        gesture: HotkeyGesture::with_shift(Key::R),
        scope: HotkeyScope::Focus(FocusContext::Waveform),
        command: HotkeyCommand::ReverseSelection,
    },
    HotkeyAction {
        id: "reverse-selection-browser",
        label: "Reverse selection",
        gesture: HotkeyGesture::with_shift(Key::R),
        scope: HotkeyScope::Focus(FocusContext::SampleBrowser),
        command: HotkeyCommand::ReverseSelection,
    },
    HotkeyAction {
        id: "fade-selection-left-to-right",
        label: "Fade selection (left to right)",
        gesture: HotkeyGesture::new(Key::Backslash),
        scope: HotkeyScope::Focus(FocusContext::Waveform),
        command: HotkeyCommand::FadeSelectionLeftToRight,
    },
    HotkeyAction {
        id: "fade-selection-right-to-left",
        label: "Fade selection (right to left)",
        gesture: HotkeyGesture::new(Key::Slash),
        scope: HotkeyScope::Focus(FocusContext::Waveform),
        command: HotkeyCommand::FadeSelectionRightToLeft,
    },
    HotkeyAction {
        id: "mute-selection",
        label: "Mute selection",
        gesture: HotkeyGesture::new(Key::M),
        scope: HotkeyScope::Focus(FocusContext::Waveform),
        command: HotkeyCommand::MuteSelection,
    },
];
